### ISSUE TITLE
What are those 8 Labels?

### ISSUE THREAD

**Issue by hsiaocy** [Featuretools/Automated-Manual-Comparison#5]
Dear @WillKoehrsen,

Thanks for your amazing article and I really appreciate this work.
But I have something confused while reading at the end of **Metrics** section, you said "One customer, **8 different labels.** It seems like it might be difficult to predict this customer's spending given her fluctuating total spending! We'll have to see if Featuretools is up to the task."

I don't understand those **8 different labels** you mentioned here, is it a binarized label issue?
Could you please explain it?
Thank you very much!!

Allen

**Comment by WillKoehrsen** [comment]
A customer can have 8 different labels because we have data on them for 8 different months. Each label corresponds to the spending for one customer for one month. 

This is why the concept of cutoff times are so crucial. For each label, we can only use data from before the cutoff time to make features for that label. 

Does that make sense?

**Comment by hsiaocy** [comment]
I see. I can completely understand your idea.
Thanks a lot!

**Comment by WillKoehrsen** [comment]
Great. I'll close the issue then. If something else isn't clear, don't hesitate to ask!
