### ISSUE TITLE
How can I use featuretools with only one table?

### ISSUE THREAD

**Issue by xuzhang5788** [Featuretools/Automated-Manual-Comparison#7]
If I have a dataset with only one table, how to use featuretools? If the whole features are all Continuous Numeric Data, is the featuretools still useful? Many thanks.

**Comment by WillKoehrsen** [comment]
This is probably a better question for [Stack Overflow](http://stackoverflow.com) (tagged [with Featuretools](https://stackoverflow.com/questions/tagged/featuretools) so we see it!). The [Retail Spending Notebook](https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Retail%20Spending/notebooks/Automated%20Retail%20Spending.ipynb) shows how to use Featuretools with only a single table by normalizing entities from the table. 

Another example of using Featuretools for a single table can be found in this Kaggle Kernel: [Featuretools for Good](https://www.kaggle.com/willkoehrsen/featuretools-for-good). Featuretools is still useful even when you can't normalize entities because you can still apply [`transform` primitives](https://docs.featuretools.com/automated_feature_engineering/primitives.html) to the table which act on a single or multiple columns in one table.
